bind 0.0.0.0
protected-mode yes
port {{port}}
requirepass {{password}}
masterauth {{password}}
appendonly yes
dir /data
cluster-enabled yes
cluster-config-file /data/nodes.conf
cluster-node-timeout 5000
cluster-announce-ip {{__ip}}
cluster-announce-port {{port}}
cluster-announce-bus-port {{__bus_port}}
