port {{sentinel_port}}
bind 0.0.0.0
protected-mode yes
dir /tmp
requirepass {{password}}
sentinel monitor {{master_name}} {{__master_ip}} {{__master_port}} {{__quorum}}
sentinel auth-pass {{master_name}} {{password}}
sentinel down-after-milliseconds {{master_name}} 5000
sentinel parallel-syncs {{master_name}} 1
sentinel failover-timeout {{master_name}} 10000
sentinel announce-ip {{__ip}}
sentinel announce-port {{sentinel_port}}
