port {{sentinel_port}}
bind 0.0.0.0
protected-mode yes
dir /tmp
requirepass {{password}}
sentinel monitor mymaster {{__master_ip}} {{__master_port}} {{__quorum}}
sentinel auth-pass mymaster {{password}}
sentinel down-after-milliseconds mymaster 5000
sentinel parallel-syncs mymaster 1
sentinel failover-timeout mymaster 10000
sentinel announce-ip {{__ip}}
sentinel announce-port {{sentinel_port}}
