bind 0.0.0.0
protected-mode yes
port {{port}}
requirepass {{password}}
masterauth {{password}}
appendonly yes
dir /data
replica-announce-ip {{__ip}}
replica-announce-port {{port}}
replicaof {{__master_ip}} {{__master_port}}
